<?php

use Airwallex\Payments\Helper\Configuration;
use Magento\Framework\App\ObjectManager;

$configuration = ObjectManager::getInstance()->get(Configuration::class);
$area = $configuration->expressDisplayArea();

if ($configuration->isExpressActive() && strpos($area, $block->getData('from')) !== false): ?>
<div data-bind="scope: 'airwallex-express'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "airwallex-express": {
                        "component": "Airwallex_Payments/js/view/payment/method-renderer/express-checkout",
                        "from": "<?= $escaper->escapeHtml($block->getData('from')) ?>",
                        "template": "Airwallex_Payments/payment/express-checkout"
                    }
                }
            }
        }
    }
</script>
<?php endif; ?>
