<div data-bind="scope: 'airwallex-express'">
<?php
require __DIR__ . '/../web/template/payment/express-checkout.html';
?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "airwallex-express": {
                        "component": "Airwallex_Payments/js/view/payment/method-renderer/express-checkout",
                        "from": "<?=$block->getData('from')?>"
                    }
                }
            }
        }
    }
</script>
