<script>
    require([
            'domReady!',
            'Airwallex_Payments/js/view/payment/method-renderer/express-checkout',
            'jquery',
        ],
        function (domReady, airwallexPayments, $) {
            let obj = airwallexPayments()
            obj.loadPayment()
        });
</script>

<div class="airwallex-express-checkout">
    <div class="aws-button-mask"></div>
    <div class="google-pay" id="awx-google-pay-container">
        <div id="awx-google-pay"></div>
    </div>
</div>

<div id="awx-modal">
    <div class="modal-body-content"></div>
</div>
