<?php

use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block */

$ccNumberView = $block->getNumberLast4Digits();
$brand = $block->getBrand();
$cardCustomerId = $block->cardCustomerId();
$currentCustomerId = $block->currentCustomerId();
?>
<?php if ($cardCustomerId === $currentCustomerId && $block->getStatus() === 'VERIFIED') {?>
<tr>
    <td data-th="<?= __('Card Number') ?>" class="col card-number">
        <span><?= __('ending') ?></span> <?= /* @noEscape */ $ccNumberView ?>
    </td>
    <td data-th="<?= __('Expiration Date') ?>" class="col card-expire">
        <?= $block->getExpDate() ?>
    </td>
    <td data-th="<?= __('Type') ?>" class="col card-type">
        <img alt="icon" src="<?= /* @noEscape */ $block->getIconUrl() ?>"
             width="<?= /* @noEscape */ $block->getIconWidth() ?>"
             height="<?= /* @noEscape */ $block->getIconHeight() ?>"
        >
    </td>
    <td data-th="<?= __('Actions') ?>" class="col actions">
        <form id="form-<?= $block->getToken()->getGatewayToken() ?>"
            class="form"
            action="<?= $block->getUrl('vault/cards/deleteaction') ?>"
            method="post"
            >
            <?= $block->getBlockHtml('formkey') ?>
            <input
                name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                type="hidden"/>
            <button type="button" id="delete-<?= $block->getToken()->getGatewayToken() ?>" class="action delete">
                <span><?= __('Delete') ?></span>
            </button>
        </form>
    </td>
</tr>
<?php } ?>
<script type="text/javascript">
    require([
        'jquery',
        'mage/url'
    ], function ($, url) {
        $(document).ready(function() {
            let id = '<?= $block->getToken()->getGatewayToken() ?>';
            $(document).on('click', '#delete-' + id, function (event) {
                event.preventDefault();
                $.mage.confirm({
                    title: $.mage.__('Delete saved card'),
                    buttons: [{
                        text: $.mage.__('Delete'),
                        class: 'action-primary action-accept',
                        click: function() {
                            $('body').trigger('processStart');
                            this.closeModal(event, true);
                            let removeUrl = url.build('rest/V1/airwallex/saved_cards/') + id;

                            $.ajax({
                                url: removeUrl,
                                method: 'DELETE',
                                success: (function() {
                                    $('#form-' + id).trigger('submit');
                                }).bind(this),
                                error: function() {
                                    $('body').trigger('processStop');
                                    $('.modal-content div').html('');
                                }
                            });
                        }
                    }, {
                        text: $.mage.__('Cancel'),
                        click: function(event) {
                            this.closeModal(event, true);
                            $('.modal-content div').html('');
                        }
                    }]
                });
                let msg = 'You are deleting your saved <?=$brand?> card ending in <?=$ccNumberView?>.';
                $('.modal-content div').html($.mage.__(msg));

            });
        });
    });
</script>
