<script>
    require([
            'jquery'
        ],
        function (jQuery) {
            window.addEventListener('load', function () {
                let type = '<?= $this->type ?>';
                let payElement = jQuery('[name="groups[airwallex_payments][groups][card][groups][express][fields][' + type + '_pay_active][value]"]');
                let tipElement = jQuery('#express-' + type + '-enable-tips');

                let enablePayments = function () {
                    tipElement.html("");
                    let selectedValue = payElement.val();
                    if (selectedValue === '0') {
                        return;
                    }
                    jQuery('body').trigger('processStart');
                    new Ajax.Request('<?= $block->escapeJs($block->getUrl('airwallex/configuration/PayEnable')) ?>', {
                        parameters: {"methods": type + '_pay'},
                        type: "POST",
                        loaderArea:     false,
                        asynchronous:   true,
                        onCreate() {
                        },
                        onSuccess(response) {
                            if (response && response.responseJSON && response.responseJSON.type === 'error') {
                                let tip = response.responseJSON.message;
                                if (document.querySelector('[name="groups[airwallex_payments][groups][basic][fields][mode][value]"]').value === 'prod') {
                                    tip = tip.replace('demo.airwallex', 'www.airwallex');
                                }
                                tipElement.html(tip);
                            }
                        },
                        onFailure(xhr) {
                        },
                        onComplete() {
                            jQuery('body').trigger('processStop');
                        }
                    });
                };
                payElement.on('change', enablePayments);
                let activeSelector = '[name="groups[airwallex_payments][groups][card][groups][express][fields][active][value]"]';
                jQuery(activeSelector).on('change', () => {
                    if (jQuery(activeSelector).val() === '0') return;
                    enablePayments();
                });
            });
        });
</script>
<p id="express-<?= $this->type ?>-enable-tips" style="color: red; margin-top: 10px;"></p>
