<?php /** @var \Airwallex\Payments\Model\Config\Adminhtml\UpdateSettings $block */ ?>
<script>
    require([
            'jquery'
        ],
        function (jQuery) {
            let accountStr = '<?= $this->getAccount() ?>';
            let account = accountStr ? JSON.parse(accountStr) : {};
            let typeSelector = '[name="groups[airwallex_payments][groups][basic][fields][mode][value]"]';
            let env = document.querySelector(typeSelector).value;

            // jQuery(document).ready(function () {
            //     if (account[env + "_account_id"]) {
            //         jQuery("#awx-connected").hide();
            //     }
            // });
            //
            // jQuery(typeSelector).on('change', () => {
            //     let env = document.querySelector(typeSelector).value;
            //     if (account[env + "_account_id"]) {
            //         jQuery("#awx-connected").hide();
            //     } else {
            //         jQuery("#awx-connected").show();
            //     }
            // });

            function uuid() {
                let S4 = function () {
                    return ((1 + Math.random()) * 0X10000 | 0).toString(16).substring(1);
                };
                return (S4() + S4() + "-" + S4() + "-" + S4() + "-" + S4() + "-" + S4() + S4() + S4());
            }

            jQuery('#airwallex_update_settings').click(function () {
                let env = document.querySelector(typeSelector).value;
                let redirectUrl = '<?= $block->escapeJs($block->getUrl('airwallex/configuration/setUpdateSettingsMessage')) ?>';
                redirectUrl += "?target_url=" + btoa(location.href) + '&env=' + env;
                let awxUrl = 'https://demo.airwallex.com/';
                if (env === 'prod') {
                    awxUrl = awxUrl.replace('demo.airwallex', 'www.airwallex');
                }
                const connectedAccountId = account[`${env}_account_id`] || '';
                const params = new URLSearchParams({
                    platform: 'magento',
                    origin: location.href,
                    returnUrl: redirectUrl,
                    requestId: uuid(),
                    connectedAccountId: connectedAccountId,
                });

                location.href = `${awxUrl.trim()}payment_app/plugin/api/v1/connection/start?${params.toString()}`;
            });
        });
</script>

<?php echo $block->getButtonHtml() ?>

<!--<div id="awx-connected" class="awx-connect-tip">-->
<!--    <div class="title">Your Airwallex plug-in is activated</div>-->
<!--    <div class="content">You can also manage which account is connected to your Magento store.</div>-->
<!--</div>-->

<style>
    .awx-connect-tip {
        margin: 10px 0;
    }

    .awx-connect-tip .title {
        font-weight: bold;
        margin-bottom: 5px;
    }
</style>
