<template id="awx-currency-switcher-template">
    <div class="awx-currency-switcher awx-apm-currency-switcher">
        <div class="awx-currency-switcher-trigger-wrap">
            <span class="awx-currency-switcher-trigger" role="button" tabindex="0"></span>
        </div>
        <div class="awx-currency-switcher-panel" style="display: none;">
            <div class="awx-currency-switcher-search">
                <input type="text" class="awx-currency-switcher-search-input" />
            </div>
            <ul class="awx-currency-switcher-list"></ul>
        </div>
    </div>
</template>
